#!/usr/bin/env python3
"""Regenerate the complete pinned Lucide pack using only Python's stdlib."""

import hashlib
import io
import json
from pathlib import Path
import re
import sys
import subprocess
import tarfile
import urllib.request

COMMIT = "59978cecf84986af59f1f9f503bcebdc89c6d166"
ARCHIVE_SHA256 = "d5c7d2a38f98c4169b13f71dfe40d1e149f4ca4b4873e1fbafb142997f738924"
URL = f"https://codeload.github.com/lucide-icons/lucide/tar.gz/{COMMIT}"
ROOT = Path(__file__).resolve().parent.parent


def generate(archive):
    assert hashlib.sha256(archive).hexdigest() == ARCHIVE_SHA256, "Unexpected Lucide archive"
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
        files = {
            member.name.split("/", 1)[1]: tar.extractfile(member).read()
            for member in tar.getmembers()
            if member.isfile() and "/" in member.name
        }

    names = sorted(path[6:-4] for path in files if re.fullmatch(r"icons/[a-z0-9-]+\.svg", path))
    assert len(names) == 1776, "Incomplete pinned Lucide set"
    assets = ROOT / "assets/lucide"
    assets.mkdir(parents=True, exist_ok=True)
    variants = []
    entries = []
    aliases = {}
    for name in names:
        variant = "".join(part.capitalize() for part in name.split("-"))
        if variant[0].isdigit():
            variant = "Icon" + variant
        assert variant not in variants, f"Rust name collision: {variant}"
        variants.append(variant)
        metadata = json.loads(files[f"icons/{name}.json"])
        for suffix in ("svg", "json"):
            (assets / f"{name}.{suffix}").write_bytes(files[f"icons/{name}.{suffix}"])
        for alias in metadata.get("aliases", []):
            alias_name = alias if isinstance(alias, str) else alias["name"]
            assert alias_name not in names and alias_name not in aliases, f"Alias collision: {alias_name}"
            aliases[alias_name] = variant
        entries.append({
            "canonical_name": name,
            "rust_name": f"LucideIcon::{variant}",
            "asset_path": f"icons/lucide/{name}.svg",
            "upstream_svg_path": f"icons/{name}.svg",
            "upstream_json_path": f"icons/{name}.json",
            "svg_sha256": hashlib.sha256(files[f"icons/{name}.svg"]).hexdigest(),
            "json_sha256": hashlib.sha256(files[f"icons/{name}.json"]).hexdigest(),
            "contributors": metadata.get("contributors", []),
            "aliases": metadata.get("aliases", []),
            "deprecated": metadata.get("deprecated", False),
            "tags": metadata.get("tags", []),
            "categories": metadata.get("categories", []),
        })

    code = ["// Generated by scripts/generate.py. Do not edit by hand.",
            "/// Every canonical icon in the pinned Lucide release.",
            "#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]", "#[repr(usize)]", "pub enum LucideIcon {"]
    for name, variant in zip(names, variants):
        code.extend([f"    /// The Lucide `{name}` icon.", f"    {variant},"])
    code.extend(["}", "impl LucideIcon {", "    /// Every canonical icon, sorted by name.",
                 f"    pub const ALL: [Self; {len(names)}] = ["])
    code.extend(f"        Self::{variant}," for variant in variants)
    code.extend(["    ];", "}", f"static ICONS: [(&str, &str, &[u8]); {len(names)}] = ["])
    for name in names:
        code.append(f'    ("{name}", "icons/lucide/{name}.svg", include_bytes!("../assets/lucide/{name}.svg")),')
    code.extend(["];", f"static ALIASES: [(&str, LucideIcon); {len(aliases)}] = ["])
    code.extend(f'    ("{name}", LucideIcon::{variant}),' for name, variant in sorted(aliases.items()))
    code.extend(["];", ""])
    (ROOT / "src/generated.rs").write_text("\n".join(code))
    subprocess.run(["rustfmt", "--edition", "2024", str(ROOT / "src/generated.rs")], check=True)
    (ROOT / "LICENSE").write_bytes(files["LICENSE"])
    manifest = {
        "schema_version": 2,
        "crate": {"name": "gpui-icons", "version": "0.2.0", "gpui_revision": "59b2ebf10351b5c0b5cd4403f01ed0460eeec06d"},
        "generator": {"name": "scripts/generate.py", "version": "0.2.0"},
        "upstream": {"repository": "https://github.com/lucide-icons/lucide", "release": "1.33.0", "commit": COMMIT,
                     "archive_sha256": ARCHIVE_SHA256},
        "licenses": {"crate_code": "MIT", "lucide_assets": "ISC with Feather-derived MIT terms", "bundle": "LICENSE and LICENSES/gpui-icons-MIT"},
        "icons": entries,
    }
    (ROOT / "RELEASE-MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Generated {len(names)} icons and {len(aliases)} aliases from Lucide 1.33.0.")


if __name__ == "__main__":
    archive = Path(sys.argv[1]).read_bytes() if len(sys.argv) > 1 else urllib.request.urlopen(URL, timeout=60).read()
    generate(archive)
